---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dscx7887/public_html/pendataan
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp public/index.php $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
    - /bin/cp -R public/build $DEPLOYPATH
    - /bin/cp -R public/storage $DEPLOYPATH
    - if [ -f public/favicon.ico ]; then /bin/cp public/favicon.ico $DEPLOYPATH; fi
    - if [ -f public/robots.txt ]; then /bin/cp public/robots.txt $DEPLOYPATH; fi
    - if [ -f public/logo.jpeg ]; then /bin/cp public/logo.jpeg $DEPLOYPATH; fi